### ISSUE TITLE
Fix check script of "1-Instructions 3.3.3 Check"

### ISSUE THREAD

**Issue by k-oyakata** [axsh/nii-project-2016#47]
1  Instructions
3.3.3  Check
After the Run Cells ...
```
Warning: Identity file ../mykeypair not accessible: No such file or directory.
THIS TASK HAS NOT BEEN DONE
```

**Comment by triggers** [comment]
This can be fixed by using an absolute path.....however...

....it also points out another issue, which is that my-script cells can change the directory, and this affects any cells run afterwards.  Although prehaps useful in some situations, it is more likely to cause confusion.    Would it be a good idea to have the extended bash kernel force each cell to start out execution in /home/centos?

**Comment by triggers** [comment]
Added export variable $default_dir and code to change to the directory path in this var before running each cell.   If default_dir='', then the feature is turned off.
https://github.com/axsh/nii-project-2016/commit/58e5815ed678e33142c5cdb06baa0e62bf21a781
